[build]
  base    = "/"
  publish = "dist"
  command = "npm run build"

[[plugins]]
  package = "netlify-plugin-fetch-feeds"
  config = {
    feeds = [
      {
        "url": "https://optus.dk/locations.geojson",
        "target": "src/locations.geojson"
      }
    ]
  }

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/locations.geojson"
  to = "/.netlify/functions/serveGeojson"
  status = 200
