[build]
  base = "/"
  publish = "dist"
  command = "npm run build"

[[plugins]]
  package = "netlify-plugin-fetch-feeds"

  [plugins.inputs]
    # Directory where fetched data should be saved
    dataDir = "src"

    # All the feeds we wish to gather for use in the build
    [[plugins.inputs.feeds]]
      name = "locations"
      url = "https://optus.dk/locations.geojson"
      target = "src/locations.geojson"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/locations.geojson"
  to = "/.netlify/functions/serveGeojson"
  status = 200
